### ISSUE TITLE
Name with number is accepted in the "add" function after filling field 

### ISSUE THREAD

**Issue by Ilona-Petenko** [NeVaper/students-rust#1]
Expected result:
Name with number was not accepted 
Actual result:
Name contains numbers
![Screenshot from 2022-05-03 23-20-29](https://user-images.githubusercontent.com/71134645/166559435-1ebcc100-a927-4c99-a876-3a52e9428fa4.png)

**Comment by DanyilSomin** [comment]
Seems to be fixed now as user can`t enter name with numbers.
![image](https://user-images.githubusercontent.com/7610811/167015508-36499d14-af43-42d8-8c5e-ad9938d16866.png)
