### ISSUE TITLE
Name with symbols  is accepted in the "add" function after the filling field

### ISSUE THREAD

**Issue by Ilona-Petenko** [NeVaper/students-rust#2]
Expected result:
Name with symbols was not accepted
Actual result:
Name contains symbols 
![Screenshot from 2022-05-03 23-22-28](https://user-images.githubusercontent.com/71134645/166559632-f4b0f592-13cd-493d-bbe6-e703afb9bc1b.png)

**Comment by DanyilSomin** [comment]
Seems to be fixed
![image](https://user-images.githubusercontent.com/7610811/167015838-8ca5c37a-c7d6-4a35-9faf-f0023adbbeae.png)
Can I close this issue now?
