### ISSUE TITLE
Birth date with future date is accepted in the "add" function after filling field

### ISSUE THREAD

**Issue by Ilona-Petenko** [NeVaper/students-rust#3]
Expected result:
Birth date with future date was not accepted
Actual result:
Birth date contains future date
![Screenshot from 2022-05-03 23-29-58](https://user-images.githubusercontent.com/71134645/166560835-f8446aec-5779-4274-9462-9468b6c6f26c.png)

**Comment by DanyilSomin** [comment]
Fixed: https://github.com/NeVaper/students-rust/commit/7707d97f39b650a2d640a58f85703f28f7fdd07c
![image](https://user-images.githubusercontent.com/7610811/167017804-7f538eae-d832-45ba-8730-658ca055a842.png)

Can I close this issue now?
