### ISSUE TITLE
The word "Chose" contains gramatical error

### ISSUE THREAD

**Issue by Ilona-Petenko** [NeVaper/students-rust#5]
Expected result:
The word "Chose" is written as "Choose"
Actual result:
The word "Chose" is written with  gramatical error
![Screenshot from 2022-05-03 23-48-14](https://user-images.githubusercontent.com/71134645/166563363-a06e791a-e352-4df3-8e49-9f8711838c11.png)

**Comment by DanyilSomin** [comment]
Fixed
https://github.com/NeVaper/students-rust/commit/bbb60965645d6e62ab969dd0e535774164d575cb
![image](https://user-images.githubusercontent.com/7610811/167015026-9bf1bb93-9eaa-4f6c-b1d1-0112eb217611.png)
