### ISSUE TITLE
The "Date" item should be named as "Birthday"

### ISSUE THREAD

**Issue by Ilona-Petenko** [NeVaper/students-rust#6]
Expected result:
The name of the item is "Date" 
Actual result:
The name of the item is "Birthday" 
![Screenshot from 2022-05-04 00-20-48](https://user-images.githubusercontent.com/71134645/166568433-743431f7-9554-4760-9e6b-74782bea402d.png)

**Comment by DanyilSomin** [comment]
Fixed: https://github.com/NeVaper/students-rust/commit/5ae77c712e64208ae41c362e17f66aa07efca608
![image](https://user-images.githubusercontent.com/7610811/167022377-17a65e33-2a2c-4d5a-9987-addc1d0d05f0.png)

**Comment by DanyilSomin** [comment]
Fixed: https://github.com/NeVaper/students-rust/commit/466f65be1dcc8408279b161ff6f75aa02a7a8c95

![image](https://user-images.githubusercontent.com/7610811/167023749-3bafcc95-2758-4a00-a059-0e918ae43dcd.png)
