### ISSUE TITLE
The "Name" field with more than 99 letters is accepted in the "add" function after filling field

### ISSUE THREAD

**Issue by Ilona-Petenko** [NeVaper/students-rust#7]
Steps to reproduce:
1. Open "Students"
2. Choose "add" option
3. Fill the "Name" field more than 99 letters 
4. Pay attention to the "Name" field contains more than 99 letters
Expected result:
Name with with more than 99 letters  was not accepted
Actual result:
Name contains more than 99 letters 

![Screenshot from 2022-05-04 22-43-48](https://user-images.githubusercontent.com/71134645/166813882-df54b9ee-dc0d-4c3a-82fb-3e0c047dec99.png)

**Comment by DanyilSomin** [comment]
Fixed (see #6)
