### ISSUE TITLE
Addition of the student wiht the "," in the "Surname" field taints file after quiting 

### ISSUE THREAD

**Issue by Ilona-Petenko** [NeVaper/students-rust#8]
1. Open "Students" 
2. Choose "file" option
3. Enter path to the file 
4. Choose "add" function 
5. Fill "Name" field with valid data 
6. Fill "Surname" field with the "," (for example "Na,me")
7. Fill "Birth date" with valid data 
8. Choose "quit" option
9. Open "Students"
10. Choose "file" option
11. Enter the same file path
12. Pay attention to the error message 

Exepted result:
File opened, no error message shown 

Actual result:
File tainted, error message was shown

![Screenshot from 2022-05-04 23-31-38](https://user-images.githubusercontent.com/71134645/166820936-a064bd2e-b118-4eb6-9c85-142ddec30398.png)

**Comment by DanyilSomin** [comment]
Seems to be fixed as user can't enter name with comma now
![image](https://user-images.githubusercontent.com/7610811/167010112-c0bafc3b-2925-4972-ac48-ef5b2dea96bb.png)

**Comment by DanyilSomin** [comment]
Can I close this issue now?

**Comment by Ilona-Petenko** [comment]
No, I have to check it
