### ISSUE TITLE
The "Id" string contains extra colon in the "delete" option 

### ISSUE THREAD

**Issue by Ilona-Petenko** [NeVaper/students-rust#9]
1. Open "Students"
2. Choose "delete" option 
3. Pay attention to the extra colon next "Id"

Exepted result:
The "Id" string contains one colon 
Actual result:
The "Id" string contains extra colon 

![Screenshot from 2022-05-04 23-39-18](https://user-images.githubusercontent.com/71134645/166823042-8ddac672-38ed-4556-a0fa-b4b8dc678908.png)
"

**Comment by DanyilSomin** [comment]
Fixed
https://github.com/NeVaper/students-rust/commit/2b2af004277de0d50fc69d9523f4ce335c184c42
![image](https://user-images.githubusercontent.com/7610811/167014323-c017dba1-6237-4a2f-a2ef-a98bf7e08b9e.png)
